const mongoose = require('mongoose');

/**
 * Notification Model
 * Generated by the Notification Agent
 */
const NotificationSchema = new mongoose.Schema({
  message: {
    type: String,
    required: [true, 'Message is required'],
    trim: true,
    maxlength: [500, 'Message cannot exceed 500 characters']
  },
  type: {
    type: String,
    enum: ['task', 'grocery', 'bill', 'service', 'system', 'family'],
    required: true
  },
  severity: {
    type: String,
    enum: ['info', 'warning', 'urgent', 'success'],
    default: 'info'
  },
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  family_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Family'
  },
  read_status: {
    type: Boolean,
    default: false
  },
  read_at: { type: Date, default: null },
  ref_id: { type: mongoose.Schema.Types.ObjectId, default: null }, // reference to related doc
  ref_model: { type: String, default: null }, // 'Task', 'Bill', 'Grocery', etc.
  action_url: { type: String, default: null }
}, {
  timestamps: { createdAt: 'timestamp', updatedAt: 'updated_at' }
});

NotificationSchema.index({ user_id: 1, read_status: 1 });

module.exports = mongoose.model('Notification', NotificationSchema);
